
import ContactStrip from '@/components/ContactStrip'
import './globals.css'
import { Montserrat } from 'next/font/google'
import Navbar from '@/components/Nav'

const Mont = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Mont.className}>
       <ContactStrip />
       <Navbar />
        {children}
        </body>
    </html>
  )
}
